### ISSUE TITLE
icons on map on partners page

### ISSUE THREAD

**Issue by morvan68** [desertfireballnetwork/websites_issues#1]
go to https://gfo.rocks/partners.html
the icons for the partners on the embedded map shows as a broken/empty image.
firefox 75.0/win10, with a bunch of adblock/disconnect like addins!

**Comment by hdevillepoix** [comment]
@morvan68 Cannot reproduce on firefox 68.7.0esr or chrome 81.0.4044.92 / debian buster.

Any particular errors popping up in the JS console?

Does the list view of partners look okay?

**Comment by hdevillepoix** [comment]
no update, closing
